version: '3'
services:
  app:
    environment:
      - EXPRESS_PORT=8080
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/app
    ports:
      - "8080:8080"
  nginx:
    environment:
      - NGINX_PORT=80
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
